swagger: "2.0"

info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article

consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /authorize/{provider}:
    get:
      operationId: provider.oauth_authorize
      tags:
        - Provider OAuth
      summary: Authorize and receive temp access token
      description: Authorize and receive temp access token
      parameters:
        - name: provider
          in: path
          description: provider name
          type: string
          required: True
      responses:
        200:
          description: Successfully retrieve this user's data
          schema:
            type: array
            items:
              properties:
                username:
                  type: string
                fname:
                  type: string
                number_of_read_items:
                  type: number    
                    
  /callback/{provider}:
    get:
      operationId: provider.oauth_callback
      tags:
        - Provider OAuth
      summary: Exchange temp access for perm access token
      description: Exchange temp access for perm access token
      parameters:
        - name: provider
          in: path
          description: provider name
          type: string
          required: True
      responses:
        200:
          description: Successfully retrieve this user's data
          schema:
            type: array
            items:
              properties:
                username:
                  type: string
                fname:
                  type: string
                number_of_read_items:
                  type: number    
  /users:
    post:
      operationId: users.authenticate_user
      tags:
        - Users
      summary: Create a new user in our database
      description: Create a new user in our database
      parameters:
        - name: user_data
          in: body
          description: user data
          required: True
          schema:
            type: object
            properties:
              id:
                type: string
                description: last name of the user
              data:
                type: object
                description: last name of the user
                properties:
                  firstName:
                    type: string
                    description: first name of the user
                  lastName:
                    type: string
                    description: last name of the user
                  imgUrl:
                    type: string
                    description: last name of the user
      responses:
        201:
          description: Successfully created a new user
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string

  /users/{user_id}:
    get:
      operationId: users.get_by_id
      tags:
        - Users
      summary: Read the entire list of books
      description: Read the list of books
      parameters:
        - name: user_id
          in: path
          description: id of the user that needs to be retrieved
          type: string
          required: True
      responses:
        200:
          description: Successfully retrieve this user's data
          schema:
            type: array
            items:
              properties:
                username:
                  type: string
                fname:
                  type: string
                number_of_read_items:
                  type: number    
                              
  /users/{user_id}/reading-library:
    get:
      operationId: users.get_reading_library
      tags:
        - Users
      summary: Read the entire reading library of this user
      description: Read the list of reading library items
      parameters:
        - name: user_id
          in: path
          description: id of the user that needs to be retrieved
          type: string
          required: True
      responses:
        200:
          description: Successfully retrieve list of books for this user
          schema:
            type: array
            items:
              properties:
                isbn:
                  type: string
                author:
                  type: string
                editions:
                  type: object

# REQUEST_TOKEN_URL = GOODREADS.BASE_URL + GENERAL.OAUTH + '/request_token',
#   AUTHORIZE_URL = GOODREADS.BASE_URL + GENERAL.OAUTH + '/authorize',
#   ACCESS_TOKEN_URL = GOODREADS.BASE_URL + GENERAL.OAUTH + '/access_token',
  
# securityDefinitions:
#   OAuth2:
#     type: oauth2
#     flow: accessCode
#     authorizationUrl: https://www.goodreads.com/oauth/authorize
#     tokenUrl: https://www.goodreads.com/oauth/access_token
#     scopes: {} # No scopes
#     description:
#       Documentation: https://www.goodreads.com/api/index