swagger: "2.0"

info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article

consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /items:
    get:
      operationId: items.get_all
      tags:
        - Items
      summary: Read the entire list of books
      description: Read the list of books
      responses:
        200:
          description: Successfully read books list operation
          schema:
            type: array
            items:
              properties:
                isbn:
                  type: string
                author:
                  type: string
                editions:
                  type: object

  /users:
    post:
      operationId: users.authenticate_user
      tags:
        - Users
      summary: Create a new user in our database
      description: Create a new user in our database
      parameters:
        - name: user_data
          in: body
          description: user data
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: first name of the user
              lname:
                type: string
                description: last name of the user

      responses:
        201:
          description: Successfully created a new user
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string

  /users/{user_id}:
    get:
      operationId: users.get_by_id
      tags:
        - Users
      summary: Read the entire list of books
      description: Read the list of books
      parameters:
        - name: user_id
          in: path
          description: id of the user that needs to be retrieved
          type: string
          required: True
      responses:
        200:
          description: Successfully retrieve this user's data
          schema:
            type: array
            items:
              properties:
                username:
                  type: string
                fname:
                  type: string
                number_of_read_items:
                  type: number    
                              
  /users/{user_id}/reading-library:
    get:
      operationId: users.get_reading_library
      tags:
        - Users
      summary: Read the entire reading library of this user
      description: Read the list of reading library items
      parameters:
        - name: user_id
          in: path
          description: id of the user that needs to be retrieved
          type: string
          required: True
      responses:
        200:
          description: Successfully retrieve list of books for this user
          schema:
            type: array
            items:
              properties:
                isbn:
                  type: string
                author:
                  type: string
                editions:
                  type: object

# securityDefinitions:
#   oauth2:
#     type: oauth2
#     flow: implicit
#     authorizationUrl: https://example.com/oauth2/dialog
#     # the token info URL is hardcoded for our mock_tokeninfo.py script
#     # you can also pass it as an environment variable TOKENINFO_URL
#     x-tokenInfoUrl: http://localhost:7979/tokeninfo
#     scopes:
#       uid: Unique identifier of the user accessing the service.